### ISSUE TITLE
playwright import error

### ISSUE THREAD

**Issue by 30Sana** [Xewdy444/CF-Clearance-Scraper#25]
Was using this just fine before but suddenly got the following error.

Command: py main.py -v -f cookies.json https://flipd.gg

Error:
Traceback (most recent call last):
  File "C:\Users\oSana\Desktop\Development\Python\Projects\FlipdBumper\CF-Clearance-Scraper\main.py", line 12, in <module>
    from playwright.sync_api import Frame, sync_playwright
  File "C:\Users\oSana\AppData\Local\Programs\Python\Python310\lib\site-packages\playwright\sync_api\__init__.py", line 25, in <module>
    import playwright.sync_api._generated
  File "C:\Users\oSana\AppData\Local\Programs\Python\Python310\lib\site-packages\playwright\sync_api\_generated.py", line 25, in <module>
    from playwright._impl._accessibility import Accessibility as AccessibilityImpl
  File "C:\Users\oSana\AppData\Local\Programs\Python\Python310\lib\site-packages\playwright\_impl\_accessibility.py", line 17, in <module>
    from playwright._impl._connection import Channel
  File "C:\Users\oSana\AppData\Local\Programs\Python\Python310\lib\site-packages\playwright\_impl\_connection.py", line 35, in <module>
    from pyee import EventEmitter
  File "C:\Users\oSana\AppData\Local\Programs\Python\Python310\lib\site-packages\pyee\__init__.py", 
line 120, in <module>
    from pyee.trio import TrioEventEmitter as _TrioEventEmitter  # noqa
  File "C:\Users\oSana\AppData\Local\Programs\Python\Python310\lib\site-packages\pyee\trio.py", line 7, in <module>
    import trio
  File "C:\Users\oSana\AppData\Local\Programs\Python\Python310\lib\site-packages\trio\__init__.py", 
line 19, in <module>
    from ._core import TASK_STATUS_IGNORED as TASK_STATUS_IGNORED  # isort: skip
  File "C:\Users\oSana\AppData\Local\Programs\Python\Python310\lib\site-packages\trio\_core\__init__.py", line 9, in <module>
    from ._entry_queue import TrioToken
  File "C:\Users\oSana\AppData\Local\Programs\Python\Python310\lib\site-packages\trio\_core\_entry_queue.py", line 129, in <module>
    @attr.s(eq=False, hash=False, slots=True)
TypeError: attrs() got an unexpected keyword argument 'eq'

**Comment by Xewdy444** [comment]
It appears that you have an outdated version of pyee or attrs. Running `pip install -U pyee attrs` should fix the issue.
