### ISSUE TITLE
Error in js solving

### ISSUE THREAD

**Issue by Tutunova** [Xewdy444/CF-Clearance-Scraper#5]
C:\Users\Usuario\Downloads\CF-Clearance-Scraper>python main.py -u https://www.bang.com/ -f cookies.txt -v
[00:33:07] Checking for cloudflare challenge...
[00:33:08] Cloudflare challenge detected. Fetching cf_clearance cookie...
[00:33:08] Launching headless browser...
[00:33:09] Going to https://www.bang.com/...
[00:33:10] Solving cloudflare challenge [JavaScript]...
Traceback (most recent call last):
  File "main.py", line 208, in <module>
    main()
  File "main.py", line 185, in main
    cookies = get_cookies(args)
  File "main.py", line 100, in get_cookies
    solve_challenge(page)
  File "main.py", line 49, in solve_challenge
    verify_button = page.get_by_role("button", name=verify_button_pattern)
AttributeError: 'Page' object has no attribute 'get_by_role'

**Comment by Xewdy444** [comment]
What version of playwright do you have installed?

**Comment by Tutunova** [comment]
Hello i'm using playwright version 1.25.1

**Comment by Xewdy444** [comment]
Please install the latest version of playwright (1.27.1). Run `pip install -U playwright` or `pip install playwright==1.27.1`. You may also have to reinstall webkit after doing so (Refer back to the README.md).

**Comment by Tutunova** [comment]
Thank you, that fixed it.
