### ISSUE TITLE
Crash with undetected-chromedriver version

### ISSUE THREAD

**Issue by MSxDOS** [Xewdy444/CF-Clearance-Scraper#72]
```
main.py -v -f cookies.json https://nowsecure.nl
[02:19:58] [INFO] Launching headless browser...
Traceback (most recent call last):
  File "<path>\main.py", line 332, in <module>
    main()
  File "<path>\main.py", line 250, in main
    with CloudflareSolver(
         ^^^^^^^^^^^^^^^^^
  File "<path>\main.py", line 84, in __init__
    self.driver = Chrome(options=options)
                  ^^^^^^^^^^^^^^^^^^^^^^^
  File "<path>\Python\Python312\site-packages\undetected_chromedriver\__init__.py", line 372, in __init__
    options.binary_location = (
    ^^^^^^^^^^^^^^^^^^^^^^^
  File "<path>\Python\Python312\site-packages\selenium\webdriver\chromium\options.py", line 54, in binary_location
    raise TypeError(self.BINARY_LOCATION_ERROR)
TypeError: Binary Location Must be a String
```

**Comment by Xewdy444** [comment]
Are you using the latest versions of selenium and undetected-chromedriver? Try running `pip install -r requirements.txt`

**Comment by MSxDOS** [comment]
It made no difference. I already had the matching versions installed according to `pip list`.

Testing on Windows 11 machine with Python 3.12.6

**Comment by Xewdy444** [comment]
You need to download and install [Google Chrome](https://www.google.com/chrome/).
